# Generated by Django 3.1.7 on 2021-04-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sumissions',
            new_name='Submission',
        ),
    ]
