# Generated by Django 3.1.7 on 2021-04-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210408_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
