# Generated by Django 3.1.7 on 2021-04-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210409_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='average_degree',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='cpl',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='density',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='diameter',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='edges',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='nodes',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
