# Generated by Django 3.1.7 on 2021-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210414_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='average_degree',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='cpl',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='density',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='diameter',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='edges',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='nodes',
            field=models.FloatField(null=True),
        ),
    ]
