# Generated by Django 3.1.7 on 2021-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210414_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='crucial_nodes',
        ),
        migrations.AddField(
            model_name='result',
            name='top_5_bc_nodes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='top_5_degree_nodes',
            field=models.TextField(null=True),
        ),
    ]
