# Generated by Django 3.1.7 on 2021-04-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210414_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='attack_tolerance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='failure_tolerance',
            field=models.TextField(null=True),
        ),
    ]
